### ISSUE TITLE
Error Reply URL is not matching

### ISSUE THREAD

**Issue by ashusah2** [OfficeDev/O365-EDU-AspNetMVC-Samples#5]
This is the intermittent issue, when ever user trying to link the office365 account the adfs page is throwing the 

"The reply address 'https://edugraphapi-ashok.azurewebsites.net/api/admin/consented' does not match the reply addresses configured for the application: 'a224510b-6eb8-477f-9b02-7831a3173cc8'. More details: not specified"

I did checked and the entry is in place and as mentioned on GitHub page, 

Admin Page is coming blank and not getting the option for the creation of schools

**Comment by astlivecomau** [comment]
the documentation does not match the new Azure Portal App registration, its impossble for me to configure it right; i get the same error as here
 how to resolve that?
